### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by kaygor16** [bertt/Advantech.Adam#1]
Hi there,

I am using the Visual Studio 2019, and try to run this project demo.

I always get the issue below when I tried to run through this code:
- modbus.ReadCoilStatus(IdSartForInputChanel, TotalDigitalInputChannels, out digitalInputChannels);
-var res = modbus.ForceSingleCoil(IdSartForOutputChannel+channel, val);

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Advantech.Protocol, Version=8.2.7.0, Culture=neutral, PublicKeyToken=c24039c75946be9c' or one of its dependencies. The system cannot find the file specified.
  Source=Advantech.Adam
  StackTrace:
   at Advantech.Adam.Modbus.PresetMultiRegs(Int32 i_iStartReg, Int32 i_iTotalReg, Int32 i_iTotalByte, Byte[] i_byData)
   at Advantech.Adam.AdamSocket.AdamTCPTransaction(String i_szSend, String& o_szRecv)
   at Advantech.Adam.AdamBase.ASCIISendRecv(String i_szSend, String& o_szRecv)
   at Advantech.Adam.Configuration.GetFirmwareVer(String& o_szVer)
   at Advantech.Adam.Adam6060.GetFirmWareVersion() in D:\Advantech.Adam-master\Adam6060.cs:line 34
   at Advantech.Adam.Program.Adam6060Demo(String ipAdam6060) in D:\Advantech.Adam-master\Program.cs:line 54
   at Advantech.Adam.Program.Main() in D:\Advantech.Adam-master\Program.cs:line 11

Is there any reference I needed or missed in order to resolve this?

**Comment by bertt** [comment]
Hi, my guess is to install some drivers, see https://www.advantech.com/search/?q=ADAM-6060&st=support&sst=Driver&from=support
